config:
  root_domain: webb.app
  root_domain_email: "adrian@webb.sh"

  aws_networks:
    - aws-us-east-1

  admin_host_name: admin

  aws_admin_machine: t2.medium

  admin_db_max_connections: 10
  admin_thread_count: 20
  admin_terraform_max_processes: 10
  admin_ansible_max_processes: 10

  cenv_database: "%%cenv_database:30"
  cenv_database_user: "%%cenv_database_user:30"
  cenv_password: "%%cenv_password:30"
