version: '3.7'

x-mcmi: &mcmi
    image: ${MCMI_DEFAULT_RUNTIME_IMAGE}
    restart: always
    environment:
      MCMI_API_PORT: 5123
    env_file: .env
    depends_on:
      - data
      - tasks

services:
  lb:
    image: eeacms/haproxy:1.8-1.5
    restart: always
    environment:
      FRONTEND_PORT: "5123"
      FRONTEND_MODE: tcp
      BACKENDS: api
      BACKENDS_PORT: "5123"
      BACKENDS_MODE: tcp
      BALANCE: roundrobin
      DNS_ENABLED: "true"
      LOG_LEVEL: warning
      INTER: 5s
    depends_on:
      - api
    ports:
      - "5123:5123"
      - "1936:1936"

  api:
    << : *mcmi
    entrypoint: mcmi-api

  scheduler:
    << : *mcmi
    entrypoint: mcmi-scheduler

  worker:
    << : *mcmi
    entrypoint: mcmi-worker
