version: '3.7'

x-mcmi: &mcmi
    image: ${MCMI_DEFAULT_RUNTIME_IMAGE}
    restart: always
    env_file: .env

services:
  api:
    << : *mcmi
    entrypoint: mcmi-api
    ports:
      - "5123:5123"

  scheduler:
    << : *mcmi
    entrypoint: mcmi-scheduler

  worker:
    << : *mcmi
    entrypoint: mcmi-worker
