
_command: &command
  provider: remote_command
  roles: server-admin
  servers:
    - name.startswith=mcmi-


environment:
  <<: *command
  command: env | grep 'MCMI_' > @env_file
  options:
    env_file: ~/.env

update:
  <<: *command
  command: docker-compose rm -fs @service && docker-compose pull && docker-compose up -d && docker image prune -fa
  options:
    service: "api scheduler worker"

restart:
  <<: *command
  command: docker-compose restart @service
  options:
    service: "api scheduler worker"

log:
  <<: *command
  command: docker-compose logs --tail=@count @service
  options:
    count: 100
    service: "api scheduler worker"
