config:
  root_domain: example.com
  root_domain_email: "someone@example.com"

  admin_group: mcmi

  admin_server_host_name: admin
  admin_server_name: mcmi-admin
  admin_server_group: mcmi-admin
  admin_server_database: "%%mcmi_server_database:30"
  admin_server_database_user: "%%mcmi_server_database_user:30"
  admin_server_password: "%%mcmi_server_password:30"

  admin_cluster_name: mcmi
  admin_cluster_group: mcmi-cluster
  admin_cluster_database: "%%mcmi_cluster_database:30"
  admin_cluster_database_user: "%%mcmi_cluster_database_user:30"
  admin_cluster_password: "%%mcmi_cluster_password:30"

  admin_subnet_cidr_prefix: 28
  admin_subnet_public_ip: true

  admin_port: 5123
  admin_data_dir: /var/local/data

  admin_parallel: true
  admin_db_max_connections: 1
  admin_thread_count: 10
  admin_terraform_max_processes: 10
  admin_ansible_max_processes: 10
